bluetooth_manager:
  default:
    bluetoothctl_path: "/usr/bin/bluetoothctl"
    max_connections: 4
    logging:
      level: "INFO"
      format: "%(asctime)s - %(levelname)s - %(message)s"
      file: "logs/bluetooth_manager.log"
    retry:
      enable: true
      max_attempts: 3
      delay_seconds: 2
    scan:
      timeout_seconds: 10
      duration: 12  # Duration for which the scan is active, in seconds
      device_regex: "Device (\\S+) "  # Regex to extract device information from output
    connection:
      response_timeout: 5
      expected_response: "Connection successful"
    disconnect:
      timeout_seconds: 5  # Timeout for disconnect operation
    list:
      timeout_seconds: 5  # Timeout for list operation
      device_regex: "Device (\\S+) Connected: yes"  # Regex to match connected devices

  channel_1:
    max_connections: 2
    retry:
      enable: true
      max_attempts: 5
      delay_seconds: 3

  channel_2:
    max_connections: 6
    retry:
      enable: false

  channel_3:
    max_connections: 3
    retry:
      enable: true
      max_attempts: 4
      delay_seconds: 1