bluetooth_manager:
  max_connections: 5
  logging:
    file: ./logs/bluetooth_manager.log
    level: INFO
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  scan:
    timeout_seconds: 10
    device_regex: 'Bluetooth Device (.*?)\s'
  connection:
    response_timeout: 15
    expected_response: 'connected'
